### PR TITLE
Delete duplicate files

### PR DESCRIPTION
**Pull request by paulmasson**
These files have been copied elsewhere. This is simply cleanup.

### CODE REVIEW

**Comment by paulmasson** [comment]
@theo-armour because of the directory renaming this PR had no effect...

**Comment by theo-armour** [comment]
@paulmasson 

Would you like to try again?

**Comment by paulmasson** [comment]
@theo-armour will do once I understand the structure of things. The top-most `index.html` used to point to a file in the folder of iterations, which I liked. Currently that index file is the complete latest version. Is that right? What is your work flow? Which file am I supposed to edit?

**Comment by theo-armour** [comment]
@paulmasson 

I heart the old structure too.

The issue is that peeps share the link in the address bar and do not share the canonical link.

This means they always share out-of-date links. if you can think of an answer around this, it would be great.

**Comment by paulmasson** [comment]
@theo-armour you can modify the link in the address bar with `window.history.pushState()` after the page loads: that way there would always be a canonical link to share. You could also modify the index files, both root and dev, to use the first from last and last files in a standard folder of iterations, so you would no longer need to do anything manual when moving to new versions.

The question remains: which file do you intend I should modify? The one in apps? What is this "app" thing anyway?

Or would you rather implement the changes described and save yourself the extra build state of the "app"?

**Comment by theo-armour** [comment]
@paulmasson 

> you can modify the link in the address bar with window.history.pushState() after the page loads: that way there would always be a canonical link to share. 

Excellent idea. I've never tried anything like this. Can you build an example somewhere?

> You could also modify the index files, both root and dev, to use the first from last and last files in a standard folder of iterations, so you would no longer need to do anything manual when moving to new versions.

Same as above. And I have even less of an idea how to implement.

> The question remains: which file do you intend I should modify?

I am using date versioning as in: filename-2020-03-16-17.html as in yr-mo-da-hr. So version closest to current time wins

> "apps"  

a short folder name to get files outside of repo root. was merely for tidiness.

***

Can you set up a demo in a folder somewhere inside a folder named "cookbook?

***

BTW, I really prefer using issues for these sorts of discussions. I find I lose track of really good dialogues when they are buried in places like this.

**Pull request merged**
