### PR TITLE
Update pushState in stable

### PR DESCRIPTION
**Pull request by paulmasson**

### CODE REVIEW

**Comment by paulmasson** [comment]
@theo-armour you were supposed to rearrange the directory structure before starting a new dev. Since you haven't, please merge this ASAP.

**Comment by theo-armour** [comment]
@paulmasson 

I was planning to do that when I finish real coding - in a few hours, with you looking over my shoulder. Is that OK?

**Comment by paulmasson** [comment]
@theo-armour fine for directory structure, but in the meantime merge this update please!

**Comment by paulmasson** [comment]
@theo-armour thank you! Please also try to adjust the flare of the new cones to be a percentage relative to all cases, as I texted you yesterday. Happy coding!

**Pull request merged**
